# -*- coding: utf-8 -*-
"""vamshi_ineuron.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZX4lFMHggF-yGUIJfCIIvAmSnRQVZSqr
"""

def myfilter(fun,a):
  l=[i for i in a if fun(i)==True]
  return l

[i for i in "ACADGILD"]

a=["x","y","z"]
b=[i*j for i in a for j in range(1,5)]
b

c=[i*j for i in range(1,5) for j in a]
c

list1=[2,3,4]
d=[[i+j] for i in list1 for j in range(0,3)]
d

list2=[2,3,4,5]
k=[[i+j for i in list2] for j in range( 0,4)]
k

list3=[1,2,3]
p=[(j,i) for i in list3 for j in range(1,4)]
p

#Task1:3#
def longestWord(n):
    l=[]
    for i in range(n):
        s=input("enter a word")
        l.append(s)
    print("list of words",l)
    print("longest word",max(l))
def main():
    n=int(input("enter a length of list"))
    longestWord(n)
main()

#Task2:1-1#
class Triangle:
    def __init__(self):
        self.a=None
        self.b=None
        self.c=None
    def read(self):
        self.a=int(input("enter 1st side"))
        self.b=int(input("enter 2nd side"))
        self.c=int(input("enter 3rd side"))
    def print(self):
        print(self.a,self.b,self.c)
class Area(Triangle):
    def __init___(self):
        self.s=None
        self.a1=None
    def area(self):
        self.s=(self.a+self.b+self.c)/2
        self.a1=(self.s*(self.s-self.a)*(self.s-self.b)*(self.s-self.c))**0.5
        print("area of triangle",self.a1)
def main():
    ar=Area()
    ar.read()
    ar.print()
    ar.area()
main()

#Task 2:1-2#
def filter_long_words(n):
    w=[]
    for i in range(n):
        string=input("enter a word")
        w.append(string)
    print("original list",w)
    l=[]
    for i in w:
        if len(i)>n:
            l.append(i)
    print("longest word than  lenght of list",l)
def main():
    n=int(input("enter length of list"))
    filter_long_words(n)
main()

#Task2:2-1#
def length(n):
    string=[ input("enter  a word") for i in range(n)]
    print(string)
    l=[]
    for i in string:
        l.append(len(i))
    print(l)
def main():
    n=int(input("length"))
    length(n)
main()

#Task 2-2#
def vowel(s):
    char="aeiouAEIOU"
    if s  in char:
        print(True)
    else:
        print( False)
def main():
    s=input("enter any character to check whether it is a vowel or not")
    vowel(s)
main()